CONTAINER tool_AMa_1D_Snap
{
NAME tool_AMa_1D_Snap;
GROUP AMa_1DSNAP_GR1
{
BOOL AMa_1DSNAP_TO_INVIS {}
LONG AMa_1DSNAP_AX
{
	CYCLE
	{
		AMa_1DSNAP_AX_GLOB;
		AMa_1DSNAP_AX_LOCAL;
		AMa_1DSNAP_AX_ROOT;
		AMa_1DSNAP_AX_PARE;
		AMa_1DSNAP_AX_CAM;
		AMa_1DSNAP_AX_FROM_O;
		AMa_1DSNAP_AX_FREE;
	}
}
LINK AMa_1DSNAP_LINK { ACCEPT { Obase; } }
}
}