////////////////////////////////////////////////////////////////
// general.h
////////////////////////////////////////////////////////////////
// General Definitions class include
////////////////////////////////////////////////////////////////
// V0.1 2008.10.23 Robert Templeton
////////////////////////////////////////////////////////////////
#ifndef _GENERAL_H_
#define _GENERAL_H_

// Preprocessor Directives found throughout source
// C4D_R95				- if compiling with R9.5+ API
// C4D_R96				- if compiling with R9.6+ API
// C4D_R10				- if compiling with R10+ API
// C4D_R105				- if compiling with R10.5 API
// C4D_R11				- if compiling with R11 API
// C4D_R12				- if compiling with R12 API
// MACOS_R11			- if compiling MacOS with R11 API
// MACOS				- if compiling for MacOS target
// CODEWARRIOR			- if compiling for MacOS PPC target
// XCODE				- if compiling for MacOSX UB target
// OS64					- if compiling for Windows XP Pro x64 or MacOSX 11 target
// DEVELOPMENT			- to include development assistance information

#include "c4d.h"

#ifndef	_MY_C4D_SYMBOLS_H_
#define	_MY_C4D_SYMBOLS_H_
#include "c4d_symbols.h"
#endif	// _MY_C4D_SYMBOLS_H_


#if API_VERSION >= 11000
#define C4D_R11
#endif
#if API_VERSION >= 12000
#define C4D_R12
#endif
#if API_VERSION >= 13000
#define C4D_R13
#endif
#if API_VERSION >= 14000
#define C4D_R14
#endif

#ifndef	C4D_R11
typedef	SWORD										WORD;
#endif

#if API_VERSION >= 12000
	typedef	BaseObject								PluginObject;
	const	Real	MAXREAL =						MAXREALr;
	const	Real	MINREAL =						MINREALr;
#else
	// const LONG R12value =	oldvalue
	// Methods
	typedef	FreeChilds										FreeChildren;
	typedef	ReadReal										ReadSReal;
	typedef	WriteReal										WriteSReal;
	typedef	GetPos											GetRelPos;
	typedef	SetPos											SetRelPos;
	typedef	GetRot											GetRelRot;
	typedef	SetRot											SetRelRot;
	typedef	GetScale										GetRelScale;
	typedef	SetScale										SetRelScale;
	// BaseObject
	const	LONG	ID_BASEOBJECT_REL_POSITION =			ID_BASEOBJECT_POSITION;
	const	LONG	ID_BASEOBJECT_REL_SCALE =				ID_BASEOBJECT_SCALE;
	const	LONG	ID_BASEOBJECT_REL_ROTATION =			ID_BASEOBJECT_ROTATION;
	// Draw
	typedef	Bool											DRAWRESULT;
	typedef	LONG											DRAWPASS;
	typedef	LONG											TOOLDRAWFLAGS;
	typedef	LONG											TOOLDRAW;
	const	LONG	TOOLDRAW_0 =							0L;
	const	LONG	TOOLDRAWFLAGS_0 =						0L;
	const	LONG	TOOLDRAWFLAGS_INVERSE_Z =				DRAWFLAGS_INVERSE_Z;
	const	LONG	TOOLDRAWFLAGS_HIGHLIGHT =				DRAWFLAGS_HIGHLIGHT;
	const	LONG	TOOLDRAW_0 =							0L;
	const	LONG	TOOLDRAW_HANDLES =						DRAW_HANDLES;
	const	LONG	TOOLDRAW_AXIS =							DRAW_AXIS;
	const	LONG	TOOLDRAW_HIGHLIGHTS =					DRAW_HIGHLIGHTS;
	// GetClone()
	const	LONG	COPYFLAGS_0 =							0L;
	const	LONG	COPYFLAGS_NO_HIERARCHY =				COPY_NO_HIERARCHY;
	const	LONG	COPYFLAGS_NO_ANIMATION =				COPY_NO_ANIMATION;
	const	LONG	COPYFLAGS_NO_BITS =						COPY_NO_BITS;
	const	LONG	COPYFLAGS_NO_BRANCHES =					COPY_NO_BRANCHES;
	const	LONG	COPYFLAGS_DOCUMENT =					COPY_DOCUMENT;
	const	LONG	COPYFLAGS_NONGONS =						COPY_NO_NGONS;
	const	LONG	COPYFLAGS_RECURSIONCHECK =				COPY_RECURSIONCHECK;
	// SplineObject
	const	LONG	SPLINETYPE_LINEAR =						Tlinear;
	const	LONG	SPLINETYPE_CUBIC =						Tcubic;
	const	LONG	SPLINETYPE_AKIMA =						Takima;
	const	LONG	SPLINETYPE_BSPLINE =					Tbspline;
	const	LONG	SPLINETYPE_BEZIER =						Thermite;
	const	LONG	SPLINEOBJECT_INTERPOLATION_NONE =		Inone;
	const	LONG	SPLINEOBJECT_INTERPOLATION_NATURAL =	Inatural;
	const	LONG	SPLINEOBJECT_INTERPOLATION_UNIFORM =	Iuniform;
	const	LONG	SPLINEOBJECT_INTERPOLATION_ADAPTIVE =	Iadaptive;
	const	LONG	SPLINEOBJECT_INTERPOLATION_SUBDIV =		Isubdiv;
	// Undos
	const	LONG	UNDOTYPE_NEW =							UNDO_NEW;
	const	LONG	UNDOTYPE_CHANGE =						UNDO_CHANGE;
	const	LONG	UNDOTYPE_DELETE =						UNDO_DELETE;
	// SetParameter
	const	LONG	DESCFLAGS_SET_0 =						0L;
	const	LONG	DESCFLAGS_SET_USERINTERACTION =			DESCFLAGS_USERINTERACTION;
	const	LONG	DESCFLAGS_SET_DONTCHECKMINMAX =			DESCFLAGS_DONTCHECKMINMAX;
	// GetParameter
	const	LONG	DESCFLAGS_GET_0 =						0L;
	// SendModellingCommand.ModelingCommandData
	const	LONG	MODELINGCOMMANDFLAGS_0 =				0L;
	const	LONG	MODELINGCOMMANDMODE_ALL =				MODIFY_ALL;
	const	LONG	MODELINGCOMMANDMODE_POINTSELECTION =	MODIFY_POINTSELECTION;
	const	LONG	MODELINGCOMMANDMODE_POLYGONSELECTION =	MODIFY_POLYGONSELECTION;
	const	LONG	MODELINGCOMMANDMODE_EDGESELECTION =		MODIFY_EDGESELECTION;
	// Filename.FileSelect
	typedef	LONG											FILESELECT;
	const	LONG	FILESELECT_LOAD =						0L;
	const	LONG	FILESELECT_SAVE =						GE_SAVE;
	const	LONG	FILESELECT_DIRECTORY =					GE_DIRECTORY;
	const	LONG	FILESELECTTYPE_ANYTHING =				FSTYPE_ANYTHING;
	const	LONG	FILESELECTTYPE_IMAGES =					FSTYPE_IMAGES;
	const	LONG	FILESELECTTYPE_SCENES =					FSTYPE_SCENES;
	const	LONG	FILESELECTTYPE_COFFEE =					FSTYPE_COFFEE;
	// BaseBitmap.Init
	const	LONG	IMAGERESULT_OK =						IMAGE_OK;
	// BaseBitmap.Save
	const	LONG	SAVEBIT_0 =								0L;
	// BaseDraw
	const	LONG	DRAWHANDLE_MINI =						HANDLE_MINI;
	const	LONG	DRAWHANDLE_SMALL =						HANDLE_SMALL;
	const	LONG	DRAWHANDLE_MIDDLE =						HANDLE_MIDDLE;
	const	LONG	DRAWHANDLE_BIG =						HANDLE_BIG;
	// GeGetSerialInfo
	const	LONG	SERIALINFO_CINEMA4D =					SERIAL_CINEMA4D;
	const	LONG	SERIALINFO_MULTILICENSE =				SERIAL_MULTILICENSE;
	// String Encoding
	const	LONG	STRINGENCODING_XBIT		=				StXbit;
	const	LONG	STRINGENCODING_8BIT		=				St8bit;
	const	LONG	STRINGENCODING_7BIT		=				St7bit;
	const	LONG	STRINGENCODING_7BITHEX	=				St7bithex;
	const	LONG	STRINGENCODING_UTF8		=				StUTF8;
	const	LONG	STRINGENCODING_HTML		=				StHTML;
	// BaseFile
	const	LONG	BYTEORDER_MOTOROLA =					GE_MOTOROLA;
	const	LONG	BYTEORDER_INTEL =						GE_INTEL;
	const	LONG	FILEOPEN_APPEND =						GE_APPEND;
	const	LONG	FILEOPEN_READ =							GE_READ;
	const	LONG	FILEOPEN_WRITE =						GE_WRITE;
	const	LONG	FILEOPEN_READWRITE =					GE_READWRITE;
	const	LONG	FILESEEK_START =						GE_START;
	const	LONG	FILESEEK_RELATIVE =						GE_RELATIVE;
	const	LONG	FILEDIALOG_NONE =						FILE_NODIALOG;
	const	LONG	FILEDIALOG_DIALOG =						FILE_ANY;
	const	LONG	FILEDIALOG_IGNOREREOPEN =				FILE_IGNOREOPEN;
	// GeGetVersionType
	const	LONG	VERSIONTYPE_PRIME =						VERSION_CINEMA4D;
	const	LONG	VERSIONTYPE_STUDIO =					VERSION_CINEMA4D;
	const	LONG	VERSIONTYPE_VISUALIZE =					VERSION_CINEMA4D;
	const	LONG	VERSIONTYPE_BROADCAST =					VERSION_CINEMA4D;
	const	LONG	VERSIONTYPE_BODYPAINT =					VERSION_BPSTANDALONE;
	const	LONG	VERSIONTYPE_BENCHMARK =					VERSION_BENCHMARK;
	const	LONG	VERSIONTYPE_UPDATER =					VERSION_UPDATER;
	const	LONG	VERSIONTYPE_INSTALLER =					VERSION_INSTALLER;
	const	LONG	VERSIONTYPE_NET_CLIENT =				VERSION_NET;
	const	LONG	VERSIONTYPE_NET_SERVER_3 =				VERSION_SERVER;
	const	LONG	VERSIONTYPE_NET_SERVER_UNLIMITED =		VERSION_SERVER;
	// -- Now GeGetSystemInfo (??)
	const	LONG	SYSTEMINFO_0 =							0L;
	const	LONG	SYSTEMINFO_DEMO =						VERSION_DEMO;
	const	LONG	SYSTEMINFO_SAVABLEDEMO =				VERSION_SAVABLEDEMO;
	const	LONG	SYSTEMINFO_SAVABLEDEMO_ACTIVE =			VERSION_SAVABLEDEMO_ACTIVE;
	// CKey
	const	LONG	CInterpolation =						CINTERPOLATION;
	// DrawViews
	const	LONG	DRAWFLAGS_0 =							0L;
	const	LONG	DRAWFLAGS_NO_THREAD =					DA_NO_THREAD;
	const	LONG	DRAWFLAGS_NO_REDUCTION =				DA_NO_REDUCTION;
	const	LONG	DRAWFLAGS_NO_ANIMATION =				DA_NO_ANIMATION;
	const	LONG	DRAWFLAGS_ONLY_ACTIVE_VIEW =			DA_ONLY_ACTIVE_VIEW;
	const	LONG	DRAWFLAGS_NO_EXPRESSIONS =				DA_NO_EXPRESSIONS;
	const	LONG	DRAWFLAGS_INDRAG =						DA_INDRAG;
	const	LONG	DRAWFLAGS_FORCEFULLREDRAW =				DA_FORCEFULLREDRAW;
	const	LONG	DRAWFLAGS_ONLY_CAMERAEXPRESSION =		DA_ONLY_CAMERAEXPRESSION;
	const	LONG	DRAWFLAGS_ONLY_BASEDRAW =				DA_ONLY_BASEDRAW;
	const	LONG	DRAWFLAGS_ONLY_HIGHLIGHT =				DA_ONLY_HIGHLIGHT;
	const	LONG	DRAWFLAGS_STATICBREAK =					DA_STATICBREAK;
	// MouseDrag
	const	LONG	MOUSEDRAGFLAGS_0 =						0L;
	const	LONG	MOUSEDRAGFLAGS_DONTHIDEMOUSE =			MOUSEDRAG_DONTHIDEMOUSE;
	const	LONG	MOUSEDRAGFLAGS_NOMOVE =					MOUSEDRAG_NOMOVE;
	const	LONG	MOUSEDRAGFLAGS_EVERYPACKET =			MOUSEDRAG_EVERYPACKET;
	const	LONG	MOUSEDRAGFLAGS_COMPENSATEVIEWPORTORG =	MOUSEDRAG_COMPENSATEVIEWPORTORG;
	const	LONG	MOUSEDRAGRESULT_CONTINUE =				MOUSEDRAG_CONTINUE;
	const	LONG	MOUSEDRAGRESULT_FINISHED =				MOUSEDRAG_FINISHED;
	// GeGetCurrentOS
	const	LONG	OPERATINGSYSTEM_WIN =					GE_WIN;
	const	LONG	OPERATINGSYSTEM_MAC =					GE_OSX;
	const	LONG	OPERATINGSYSTEM_UNIX =					GE_UNIX;
	// SaveDocument
	const	LONG	SAVEDOCUMENTFLAGS_0 =					0L;
	const	LONG	SAVEDOCUMENTFLAG_SHOWERROR =			SAVEFLAGS_DIALOGSALLOWED;
	const	LONG	SAVEDOCUMENTFLAG_SAVEAS =				SAVEFLAGS_SAVEAS;
	const	LONG	SAVEDOCUMENTFLAG_DONTADDTORECENTLIST =	SAVEFLAGS_DONTADDTORECENTLIST;
	const	LONG	SAVEDOCUMENTFLAG_AUTOSAVE =				SAVEFLAGS_AUTOSAVE;
	// GetAndCheckHierarchyClone
	const	LONG	HIERARCHYCLONEFLAGS_0 =					0L;
	const	LONG	HIERARCHYCLONEFLAGS_ASIS =				HCLONE_ASIS;
	const	LONG	HIERARCHYCLONEFLAGS_ASPOLY =			HCLONE_ASPOLY;
	const	LONG	HIERARCHYCLONEFLAGS_ASLINE =			HCLONE_ASLINE;
	const	LONG	HIERARCHYCLONEFLAGS_ASSPLINE =			HCLONE_ASSPLINE;
	// BaseDocument.GetData()
	const	LONG	DOCUMENTSETTINGS_GENERAL =				SETTINGS_GENERAL;
#endif

#endif //_GENERAL_H_